### ISSUE TITLE
Is it cryptographically random?

### ISSUE THREAD

**Issue by SomeEarthling** [SecUSo/privacy-friendly-dicer#5]

**Comment by Yonjuni** [comment]
It just uses Math.random() from java

**Comment by Yonjuni** [comment]
Added with https://github.com/SecUSo/privacy-friendly-dicer/commit/efcdf61c39b3d1ae7c7c4e1f7528b7ab8dda5cdb

Will be integrated in version 1.4.1

**Comment by SomeEarthling** [comment]
Great! Thank you.
