### ISSUE TITLE
[Feature Request] Add cryptographically random coin toss option

### ISSUE THREAD

**Issue by SomeEarthling** [SecUSo/privacy-friendly-dicer#6]

**Comment by Yonjuni** [comment]
Could you describe this in a little more detail?

**Comment by SomeEarthling** [comment]
Add in some sort of (options) field.
In it, allow users to switch to a coin instead of a dice.

Then it's now a coin flip instead of a dice roll. :)

So it will give a result of either heads or tails of a coin (50% chance of
either in each "throw" when using CPRNG).

The cryptographically random part just uses CPRNG such as:
https://developer.android.com/reference/java/security/SecureRandom.html

PS. I'm not a programmer. I don't know *how *to write the code, I just know
*what* to use.

**Comment by Yonjuni** [comment]
I guess that might be an idea for an additional Privacy Friendly App. 
I would suggest to close the issue here and I will add it to our list of apps. What do you think?

**Comment by SomeEarthling** [comment]
Sure. Your call.

I'd appreciate a way to follow your apps, then. I found then one
coincidentally.

I'd also like to stress the Secure Random function. This would really be
helpful and great seeing how your other apps are conservative on
permissions and light weight.

**Comment by Yonjuni** [comment]
Our website is secuso.org/pfa there are all published Privacy Friendly Apps. Another option is Github because there the apps are published a little earlier and then submitted to F-Droid.
