### ISSUE TITLE
Offer setting number of sides

### ISSUE THREAD

**Issue by PanderMusubi** [SecUSo/privacy-friendly-dicer#7]
In the main screen, please add a slider for the number of sides to the dice ranging from 2 up to 12. This will imply adding dice sides for 7 up to 12. Adding this will make the app suitable for certain games that require specific dice.

**Comment by Yonjuni** [comment]
Quite interesting, I have just started yesterday to explore possibilities to add more dice types. 
The current state is that the way of choosing is already defined (similar to this suggestion here). But the display of dice is still under construction.

**Comment by trymeouteh** [comment]
+1. This is all this app really needs for major features in my opinion. After adding this, just updates so this app works on newer versions of Andriod!

**Comment by shadow00** [comment]
Why limit to just 12? The D20 is also a common type of dice, and it would be nice to have a D16 (ie a hex generator) too - especially considering that you're already using a CSPRNG.

**Comment by PanderMusubi** [comment]
Yes, 16 and 20 are also good to add.

**Comment by Kamuno** [comment]
Fixed via 85180dd168a92cd130bcb03e0115731a3acc8641

However... it is currently limited to 12. I'll create a new issue for 20 sides.
